
name: Phoniex Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: # Setting up cron
    - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: choice
        options: [qa,uat]
        default: qa
        required: true

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Debug - List files
      run: |
          pwd
          find . -name "pom.xml"
    - name: Execute workflow
      working-directory: ./PhoenixTestAutomationFramework
      run: mvn clean test -DsuiteXmlFile=testng.xml -Denv="${{ github.event.inputs.env }}"

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v7.0.1
      with:
        name: Surefire Report
        path: ./PhoenixTestAutomationFramework/target/surefire-reports/
        retention-days: 10

      
